### ISSUE TITLE
Handling of secrets with GPG should be changed to sops or equivalent

### ISSUE THREAD

**Issue by karlht** [mozilla-services/sync-tps-setup#1]
Using my individual GPG key to encrypt the secrets in the config files is not a great way to do this.

Using sops would add another dependency, but I'm not sure of any other ways that get the balance of security vs. convenience right.

**Comment by rpappalax** [comment]
per conversation w/ @karlht, we will be passing in the json config as an ENV var (from Jenkins or localhost) at runtime
