### ISSUE TITLE
TPS Prod succeeds once, then fails thereafter

### ISSUE THREAD

**Issue by karlht** [mozilla-services/sync-tps-setup#13]
https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/sync.prod/19/consoleText succeeds.
Then jobs 20-22 fail.

I suspect this line:
https://github.com/mozilla-services/sync-tps-setup/blob/4b9d442b349b2e535192943e0c6de0bbcd9d82eb/Jenkinsfile#L50

needs a `sh 'rm -f tps.log.gz'` before it, because the output in
https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/sync.prod/21/consoleText

indicates `gzip: tps.log.gz already exists;	not overwritten`

**Comment by mhammond** [comment]
or maybe `gzip -f tps.log`?
