### ISSUE TITLE
Consolidate run files into one file and parametrize

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/sync-tps-setup#3]
The two run files provided are identical, with the exception of the test environment (stage|prod) being executed.  This information would be available to any Jenkins job as $TEST_ENV and would just need to be passed into the Dockerfile.

**Comment by karlht** [comment]
Not identical -- one (prod) only runs `test_sync.js` while the other (stage) runs the entire TPS suite -- there would need to be a way to parameterize the tests chosen to run.

**Comment by rpappalax** [comment]
@karlht thanks for the clarification.  in that case, it might make sense to leave them as-is
