### ISSUE TITLE
Create an nightly build Docker image of mozilla-central (source)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/sync-tps-setup#4]
The sync TPS tests require a the latest nightly source code to run.  In order to fully dockerize the tests, we'll need to provide a pre-built base docker image with this updated source code on it.

**Comment by pdehaan** [comment]
I don't know anything about Firefox source... Do we need an account to be able to do a fetch from Mercurial? Can we always just grab "latest" commit and run with it, or was this the case where we'd need to fetch after a specific time to get the code? Do we need any other tools or anything on the image? Or just some generic Docker image with Firefox source and the tests and that's it?

**Comment by rpappalax** [comment]
@pdehaan It's pretty simple and, no account needed.  https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Mercurial
pretty much, install mercurial, then clone away.

in regards to getting the desired build, i think you're right.  we do want to wait until nightly is tested, tagged and released, but i don't think we just wanna grab the latest master as it may not be stable.  let's start by seeing if we can first (1) build an image with the source code, then (2) figure out how to grab the right nightly source tree.

**Comment by karlht** [comment]
There is also a git mirror of mozilla-central available as https://github.com/mozilla/gecko-dev -- see "Steps: Get the source code" in https://developer.mozilla.org/en-US/docs/Mozilla/Projects/TPS_Tests

**Comment by rpappalax** [comment]
@karlht in that case, we'll just want to use the one that is the most intuitive, fastest and/or  reliable.

**Comment by rpappalax** [comment]
we'll pull down mozilla-central from github and pull out the dirs we need so, no need to hg clone moz central any longer
