### ISSUE TITLE
Investigate errors from "src/libcore/result.rs:906"

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/sync-tps-setup#8]
via the magnificent @rpappalax:

```
panicked at 'called `Result::unwrap()` on an `Err` value 
"No such file or directory"
/checkout/src/libcore/result.rs:906:4
```

"result.rs" sounds like maybe Rust? Not sure if we need full Firefox source, versus just the bits and pieces we're currently extracting from the ZIP file. But now armed with a starter error message above, it should hopefully be easier to Google and track down possible causes/solutions.

**Comment by rpappalax** [comment]
can't repro
